global:
  resolve_timeout: 5m
route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'sysdig-test'
receivers:
  - name: 'sysdig-test'
    webhook_configs:
#     - url: https://webhook.site/<youruuid>
#       http_config:
#         proxy_url: <yourproxy>
      - url: 'http://prometheus-msteams:2000/high_priority_channel'
