connectors:
- high_priority_channel: "https://outlook.office.com/webhook/<youruuid>"
- low_priority_channel: "https://outlook.office.com/webhook/<youruuid>"
# https://github.com/prometheus-msteams/prometheus-msteams.git
