apiVersion: v1
kind: Service
metadata:
  name: prometheus-msteams
  labels:
    name: prometheus-msteams
spec:
  type: NodePort
  ports:
    - port: 2000
      protocol: TCP
      name: 2000-tcp
  selector:
    app: prometheus-msteams